### ISSUE TITLE
Jmeter cookbook fails with chefdk-0.10.0

### ISSUE THREAD

**Issue by nkadel-skyhook** [johnbellone/jmeter-cookbook#8]
Jmeter is failing using chefdk-0.10.0 and an up-to-date "poise cokbook", as shown below.

================================================================================
Recipe Compile Error in /var/chef-solo/berks-cookbooks/jmeter/libraries/plan.rb
================================================================================

NameError
---------
uninitialized constant Chef::Resource::JmeterPlan::Poise

Cookbook Trace:
---------------
  /var/chef-solo/berks-cookbooks/jmeter/libraries/plan.rb:11:in `<class:JmeterPlan>'
  /var/chef-solo/berks-cookbooks/jmeter/libraries/plan.rb:10:in `<class:Chef>'
  /var/chef-solo/berks-cookbooks/jmeter/libraries/plan.rb:9:in `<top (required)>'

Relevant File Content:
----------------------
/var/chef-solo/berks-cookbooks/jmeter/libraries/plan.rb:

  4:  # License:: Apache 2.0
  5:  #
  6:  # Cookbook Name:: jmeter
  7:  # Library:: plan
  8:  #
  9:  class Chef
 10:    class Resource::JmeterPlan < Resource::RubyBlock
 11>>     include Poise
 12:
 13:      def initialize(name, run_context=nil)
 14:        super
 15:        @resource_name = :jmeter_plan
 16:      end
 17:
 18:      actions(:run)
 19:      attribute(:path, kind_of: String, default: lazy { node['jmeter']['plan_dir'] })
 20:    end

[2015-11-18T18:27:49-05:00] ERROR: Running exception handlers
[2015-11-18T18:27:49-05:00] ERROR: Exception handlers complete
[2015-11-18T18:27:49-05:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2015-11-18T18:27:49-05:00] ERROR: uninitialized constant Chef::Resource::JmeterPlan::Poise
[2015-11-18T18:27:49-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by sworisbreathing** [comment]
@johnbellone I just ran into this issue on a fresh wrapper cookbook. In my case, my wrapper cookbook doesn't even include any of the jmeter recipes or resources - it merely declares a dependency on the jmeter cookbook.

**Comment by sworisbreathing** [comment]
@johnbellone it looks like there's an update on master which adds `require 'poise'`, but the latest tagged release doesn't have it, which is probably why it's failing (the poise dependency isn't pinned to a major version, so that's probably why it breaks on the current tagged release)
